export interface NarratedChapter {
  id: string;
  number: string;
  title: string;
  subtitle?: string;
  /** Each entry is one line of narration and one line of transcript. */
  lines: string[];
}

/**
 * Narrative chapters. Each maps to an audio file at `/audio/{id}.mp3`.
 * The lines double as the live transcript, highlighted as audio plays.
 */
export const narratedChapters: Record<string, NarratedChapter> = {
  identity: {
    id: "identity",
    number: "01",
    title: "Identity",
    subtitle: "Before what you do.",
    lines: [
      "You are not your job.",
      "You are not your title.",
      "You understand how things connect.",
      "That is rarer than you think.",
      "Most people use systems.",
      "You see through them.",
      "You were taught to wait for permission.",
      "You do not need it.",
      "The ones who build are not different.",
      "They just started.",
    ],
  },
  freedom: {
    id: "freedom",
    number: "04",
    title: "Freedom",
    subtitle: "Underneath everything.",
    lines: [
      "Freedom is not a yacht.",
      "It is not a postcode.",
      "It is your time belonging to you.",
      "Comfort is not the same thing.",
      "A salary feels safe.",
      "Safe is not free.",
      "You do not need to leave the country.",
      "You need skills that travel.",
      "Savings that buy choices.",
      "Income that does not depend on one door.",
      "Freedom is built slowly.",
      "Skill by skill.",
      "You are already facing the right way.",
    ],
  },
  learning: {
    id: "learning",
    number: "05",
    title: "Learning",
    subtitle: "The habit that moves the others.",
    lines: [
      "You already know how to learn.",
      "You sit with a problem until it gives in.",
      "Read every day.",
      "Ideas are the cheapest leverage there is.",
      "One book can reframe a decade.",
      "Read outside your field.",
      "The best engineers are curious about everything.",
      "Write things down.",
      "Teach what you learn.",
      "Stay humble enough to be wrong.",
    ],
  },
  health: {
    id: "health",
    number: "06",
    title: "Health",
    subtitle: "The quiet foundation.",
    lines: [
      "You cannot build from a body that is failing.",
      "Health compounds both ways.",
      "You do not need to be an athlete.",
      "You need consistency.",
      "Walk.",
      "Lift something heavy.",
      "Eat real food.",
      "Guard your sleep.",
      "Everything runs on rest.",
      "Your body is the only place you have to live.",
    ],
  },
  money: {
    id: "money",
    number: "07",
    title: "Money",
    subtitle: "A tool. Nothing more.",
    lines: [
      "Money is stored freedom.",
      "It is the ability to say no.",
      "Spend less than you earn.",
      "The gap is where freedom lives.",
      "Debt is a quiet chain.",
      "Build things that pay you back.",
      "Looking wealthy and being wealthy are not the same.",
      "One is loud.",
      "The other is patient.",
      "Respect money. Do not worship it.",
    ],
  },
  business: {
    id: "business",
    number: "08",
    title: "Business",
    subtitle: "You already have the hard part.",
    lines: [
      "You understand infrastructure.",
      "That is worth more than you think.",
      "The gap between idea and built has closed.",
      "You do not have to quit tomorrow.",
      "Start something small on the side.",
      "A tool. A service. A name people trust.",
      "Ownership is the goal.",
      "Not employment.",
      "Build something that works when you leave the room.",
      "That is the beginning of a plan.",
    ],
  },
  technology: {
    id: "technology",
    number: "09",
    title: "Technology",
    subtitle: "The lever that keeps growing.",
    lines: [
      "You already live inside the machine.",
      "A laptop is the most patient partner you will ever have.",
      "Learn the fundamentals.",
      "They outlast every framework.",
      "Do not chase every trend.",
      "Build things for yourself.",
      "Small builds teach what manuals cannot.",
    ],
  },
  ai: {
    id: "ai",
    number: "10",
    title: "Artificial Intelligence",
    subtitle: "The quiet shift.",
    lines: [
      "Something has changed.",
      "One person can now build what once took a team.",
      "This is not about replacing thought.",
      "It is about removing friction.",
      "You think in systems.",
      "Point that at building.",
      "The ones who thrive are not afraid.",
      "They pick up the tools.",
      "This site is proof.",
      "Made in one sitting.",
    ],
  },
  leverage: {
    id: "leverage",
    number: "11",
    title: "Leverage",
    subtitle: "Working wider, not harder.",
    lines: [
      "Hard work is necessary.",
      "It is not enough.",
      "There are four kinds of leverage.",
      "People. Money. Code. Words.",
      "Two of them cost you nothing to start.",
      "Code works while you sleep.",
      "Words travel while you rest.",
      "Build things that work without you.",
      "Write things that teach without you.",
    ],
  },
};
