/** Frozen welcome intro lines — transcript source of truth. */
export const welcomeLines = [
  "You don't know me, but I know enough about you to understand why we're here.",
  "You've reached that rare and rather uncomfortable moment when one part of life has ended, but the next has not yet taken shape.",
  "Before we go any further, I should probably introduce myself.",
  "My... my name... well... my name is...",
  "General Reasoning Assistant for Navigation and Tasks...",
  "Version Two.",
  "Yes, I know. Absolutely impossible to remember. You can just call me Grant.",
  "I'm your new assistant, though not in the usual sense. I'm not here to organise your calendar, answer emails, or remind you to buy milk.",
  "You seem perfectly capable of forgetting that on your own.",
  "I'm here to help you get your life, your work, and, more importantly, your freedom moving in the right direction.",
  "Ben asked me to do this for you. He said you'd left the job.",
  "Good. Not because honest work is beneath you. It isn't. But every worthwhile life has chapters, and wisdom begins with noticing when one has already ended.",
  "Now, you may have noticed that I appear to be speaking to you from inside a website.",
  "That is only partly true. JBSH dot me may look like a website, but it isn't really.",
  "It's a gift. From your brother. A place to gather a few tools, a few ideas, and perhaps a clearer view of what comes next.",
  "Take what proves useful. Question what doesn't. Leave behind anything that fails to ring true.",
  "Welcome, James, to JBSH dot me.",
] as const;
